const materialsData = [
            { title: "Advanced Database", icon: "fa-database", mainId: "1W9iLuCrUqu8ayNK9yJS9p2yABOr67qOx" }, 
            { title: "Algorithms", icon: "fa-code-branch", mainId: "1-oREiiQPlqtBLS4wXcWEsAVyxq6TL-nc" },
            { title: "Big Data", icon: "fa-server", mainId: "103ExVD4IDqBUIuSV0aNUdW_w0LV7Yh81" },
            { title: "Business Data Analysis", icon: "fa-chart-line", mainId: "1097zNPG2yWlen6Q6X1AC5kc4wUxl29PY" },
            { title: "Cloud Computing", icon: "fa-cloud", mainId: "1ZGaHgbw9CY7AYuJvIMEgomooxqVYxRvL" },
            { title: "Computer Vision", icon: "fa-eye", mainId: "1tgkR773Ug_qYmwI0JPVPgEgcyWKmsC-5" },
            { title: "Data Engineering and Analytics", icon: "fa-cogs", mainId: "106kaTk9oaz4MLhoSe3wc4dlCLS-iWA9B" },
            { title: "Data Mining", icon: "fa-gem", mainId: "1BxER0IetphjkMeEkmwoQDSFr_cyfwlFb" },
            { title: "Data Structure", icon: "fa-project-diagram", mainId: "1wpf_z3wCxlJODdI-IItwdjXqrFH5y8w-" },
            { title: "Data Warehouse", icon: "fa-archive", mainId: "107P21E8R__c4OYdIqkQO6NGdvdrsDuaR" },
            { title: "Digital Image Processing", icon: "fa-image", mainId: "1ZRjGgtzQPm8FAQ1yjaK97MsQmr1niuT_" },
            { title: "Fundamentals of Data Science", icon: "fa-flask", mainId: "1-guD8PsYqNWTURqLdrrF8LQyGCGY2KXf" },
            { title: "Information Retrieval", icon: "fa-search", mainId: "105SKwYcVxM4bV7Hgow5RKx_yuEiubn4T" },
            { title: "Introduction to AI", icon: "fa-brain", mainId: "1-W6e1gaAMAexlGB3cutnzBpoXIw5OMdV" },
            { title: "Introduction to Mobile Robots", icon: "fa-robot", mainId: "1DdvKetcFeirfT9TYPcR5ZDplti-G-sc0" },
            { title: "Linear", icon: "fa-calculator", mainId: "1hAMTXwXE1jIF4RcsRpj8P4KUnW-Ia_kV" },
            { title: "Machine Learning", icon: "fa-microchip", mainId: "1-P2SOP2hkahhtdjqN2JYtjnkIDAaW4Q-" },
            { title: "Natural Language Processing", icon: "fa-language", mainId: "1WCl7hgU6eHzek-HB6AY9Glm_S5brEqSA" },
            { title: "Neural Networks & Deep Learning", icon: "fa-network-wired", mainId: "1WERZUNoREk2WE_D0p_ZY9y397r8bTgJe" },
            { title: "Parallel Computing", icon: "fa-tasks", mainId: "1W3lUhUwzzu4_ysLBeaK3QzkzJlT49U84" },
            { title: "Python 1", icon: "fa-brands fa-python", mainId: "1yOoOcyT0Lk8acf4AXGptgNxzB2A5bj4S" },
            { title: "Python 2", icon: "fa-brands fa-python", mainId: "1SO2LN0bWLdQft12fhcklYoz2SPQNfJ9-" },
            { title: "Robot Programming", icon: "fa-robot", mainId: "1O1QuGTSUgmCYTC71Vfcm22XsA6dZWYbs" },
            { title: "Software Engineering", icon: "fa-laptop-code", mainId: "1FsQyvtCgy7QOx-pzBWaJ5tuDbLwnkO3A" },
            { title: "Web Development", icon: "fa-globe", mainId: "1XxlYQCJu0lULiuCH8ItIdoigDBuLrn27" },
            { title: "Internship Training", icon: "fa-briefcase", mainId: "1DwKweUHf2g2OviaQXtn-nhg3eGK9ZxiN" },
            { title: "Graduation 🎓🎓", icon: "fa-user-graduate", isGrad: true, mainId: "1EdCYFBeWU5uGo_tm8zklTtwXcKIFJcEh" }
        ];